apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-service-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.database.url | b64enc }}
