apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-auth-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-auth-service
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
