apiVersion: v1
kind: Service
metadata:
  name: zar-auth-service
  namespace: test
spec:
  selector:
    app: zar-auth-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
