apiVersion: apps/v1
kind: Deployment
metadata:
  name: zar-auth-service
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zar-auth-service
  template:
    metadata:
      labels:
        app: zar-auth-service
    spec:
      containers:
      - name: zar-auth-service
        image: aliquis21/zar-auth-service:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: zar-auth-service-secrets
              key: DATABASE_URL
        - name: KAFKA_BOOTSTRAP_SERVERS
          valueFrom:
            configMapKeyRef:
              name: zar-auth-service-config
              key: KAFKA_BOOTSTRAP_SERVERS
        volumeMounts:
        - name: photos-storage
          mountPath: /app/photos
      volumes:
      - name: photos-storage
        persistentVolumeClaim:
          claimName: zar-photos-pvc
