version: '3'

services:
  app:
    container_name: 'shift-python-2024-auth-service'
    build:
      context: app/
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - '28082:8082'
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    environment:
      - PYTHONPATH=/workspace/src
    networks:
      - shift-network

networks:
  shift-network:
    external: true